In [49]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
le=LabelEncoder()

In [27]:
df=pd.read_csv("customer.csv")
df

,age,gender,income,city,pages_viewed,browsing_time,purchased
0,25,Male,30000.0,Chennai,5,10,0
1,32,Female,45000.0,Salem,12,20,1
2,28,Male,NaN,Coimbatore,7,15,0
3,35,Female,60000.0,NaN,15,30,1
4,twenty nine,Male,32000.0,Chennai,8,18,0
...,...,...,...,...,...,...,...
85,26,Male,29000.0,Salem,5,11,0
86,38,Female,66000.0,Chennai,16,33,1
87,31,Male,51000.0,Trichy,11,24,1
88,29,Female,35000.0,Bangalore,8,18,0
89,44,Male,78000.0,Hyderabad,20,43,1

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            90 non-null     str
 1   gender         89 non-null     str
 2   income         89 non-null     float64
 3   city           88 non-null     str
 4   pages_viewed   90 non-null     int64
 5   browsing_time  90 non-null     int64
 6   purchased      90 non-null     int64
dtypes: float64(1), int64(3), str(3)
memory usage: 5.1 KB

In [29]:
df.isnull().sum()

age              0
gender           1
income           1
city             2
pages_viewed     0
browsing_time    0
purchased        0
dtype: int64

In [30]:
df["age"]=pd.to_numeric(df["age"],errors="coerce")
df["age"]=df["age"].fillna(df["age"].mean())
df["gender"]=df["gender"].fillna(df["gender"].mode()[0])
df["city"]=df["city"].fillna("unknown")

In [31]:
df["city"]=df["city"].str.strip()
df["city"]=df["city"].str.lower()

In [32]:
df.isnull().sum()

age              0
gender           0
income           1
city             0
pages_viewed     0
browsing_time    0
purchased        0
dtype: int64

In [33]:
df["income"]=df["income"].fillna(df["income"].mean())

In [34]:
df.isnull().sum()

age              0
gender           0
income           0
city             0
pages_viewed     0
browsing_time    0
purchased        0
dtype: int64

In [35]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
85    False
86    False
87    False
88    False
89    False
Length: 90, dtype: bool

In [36]:
df[df.duplicated()]

Empty DataFrame
Columns: [age, gender, income, city, pages_viewed, browsing_time, purchased]
Index: []

In [37]:
df.drop_duplicates()

,age,gender,income,city,pages_viewed,browsing_time,purchased
0,25.000000,Male,30000.000000,chennai,5,10,0
1,32.000000,Female,45000.000000,salem,12,20,1
2,28.000000,Male,47393.258427,coimbatore,7,15,0
3,35.000000,Female,60000.000000,unknown,15,30,1
4,31.719101,Male,32000.000000,chennai,8,18,0
...,...,...,...,...,...,...,...
85,26.000000,Male,29000.000000,salem,5,11,0
86,38.000000,Female,66000.000000,chennai,16,33,1
87,31.000000,Male,51000.000000,trichy,11,24,1
88,29.000000,Female,35000.000000,bangalore,8,18,0
89,44.000000,Male,78000.000000,hyderabad,20,43,1

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            90 non-null     float64
 1   gender         90 non-null     str
 2   income         90 non-null     float64
 3   city           90 non-null     str
 4   pages_viewed   90 non-null     int64
 5   browsing_time  90 non-null     int64
 6   purchased      90 non-null     int64
dtypes: float64(2), int64(3), str(2)
memory usage: 5.1 KB

In [40]:
df=pd.get_dummies(df,columns=["gender","city"])
df

KeyError: "None of [Index(['gender', 'city'], dtype='str')] are in the [columns]"

In [41]:
df

,age,income,pages_viewed,browsing_time,purchased,gender_Female,gender_Male,city_bangalore,city_chennai,city_coimbatore,city_hyderabad,city_madurai,city_salem,city_trichy,city_unknown
0,25.000000,30000.000000,5,10,0,False,True,False,True,False,False,False,False,False,False
1,32.000000,45000.000000,12,20,1,True,False,False,False,False,False,False,True,False,False
2,28.000000,47393.258427,7,15,0,False,True,False,False,True,False,False,False,False,False
3,35.000000,60000.000000,15,30,1,True,False,False,False,False,False,False,False,False,True
4,31.719101,32000.000000,8,18,0,False,True,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,26.000000,29000.000000,5,11,0,False,True,False,False,False,False,False,True,False,False
86,38.000000,66000.000000,16,33,1,True,False,False,True,False,False,False,False,False,False
87,31.000000,51000.000000,11,24,1,False,True,False,False,False,False,False,False,True,False
88,29.000000,35000.000000,8,18,0,True,False,True,False,False,False,False,False,False,False
89,44.000000,78000.000000,20,43,1,False,True,False,False,False,True,False,False,False,False

In [42]:
df["age"]=df["age"].astype(int)

In [43]:
df

,age,income,pages_viewed,browsing_time,purchased,gender_Female,gender_Male,city_bangalore,city_chennai,city_coimbatore,city_hyderabad,city_madurai,city_salem,city_trichy,city_unknown
0,25,30000.000000,5,10,0,False,True,False,True,False,False,False,False,False,False
1,32,45000.000000,12,20,1,True,False,False,False,False,False,False,True,False,False
2,28,47393.258427,7,15,0,False,True,False,False,True,False,False,False,False,False
3,35,60000.000000,15,30,1,True,False,False,False,False,False,False,False,False,True
4,31,32000.000000,8,18,0,False,True,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,26,29000.000000,5,11,0,False,True,False,False,False,False,False,True,False,False
86,38,66000.000000,16,33,1,True,False,False,True,False,False,False,False,False,False
87,31,51000.000000,11,24,1,False,True,False,False,False,False,False,False,True,False
88,29,35000.000000,8,18,0,True,False,True,False,False,False,False,False,False,False
89,44,78000.000000,20,43,1,False,True,False,False,False,True,False,False,False,False

In [44]:
x= df.drop("purchased",axis=1)

In [45]:
y= df["purchased"]

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [55]:
lo=LogisticRegression(max_iter=1000)
de=DecisionTreeClassifier()
ra=RandomForestClassifier()
kn=KNeighborsClassifier()

In [56]:
lo.fit(x_train,y_train)
de.fit(x_train,y_train)
ra.fit(x_train,y_train)
kn.fit(x_train,y_train)

KNeighborsClassifier()

In [57]:
lo_pred=lo.predict(x_test)
de_pred=de.predict(x_test)
ra_pred=ra.predict(x_test)
kn_pred=kn.predict(x_test)

In [60]:
accuracy_lo=accuracy_score(y_test,lo_pred)
accuracy_de=accuracy_score(y_test,de_pred)
accuracy_ra=accuracy_score(y_test,ra_pred)
accuracy_kn=accuracy_score(y_test,kn_pred)

print("accuracy_lo:", accuracy_lo)
print("accuracy_de", accuracy_de)
print("accuracy_ra:", accuracy_ra)
print("accuracy_kn:", accuracy_kn)

accuracy_lo: 1.0
accuracy_de 1.0
accuracy_ra: 1.0
accuracy_kn: 1.0

In [66]:
new_data=pd.DataFrame([[30,30000,2,5,0,1,0,0,0,0,0,1,0,0]],columns=x.columns)
pred_lo_new=lo.predict_proba(new_data)
pred_de_new=de.predict(new_data)
pred_ra_new=ra.predict(new_data)
pred_kn_new=kn.predict(new_data)

print(pred_lo_new)
print(pred_de_new)
pred_ra_new
pred_kn_new

[[9.99999997e-01 2.90236251e-09]]
[0]

array([0])